apiVersion: v1
kind: Secret
metadata:
  name: trading-bot-secrets
  namespace: crypto-trading
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # echo -n "your-api-key" | base64
  binance_api_key: ""
  binance_secret_key: ""
  kraken_api_key: ""
  kraken_secret_key: ""
  openai_api_key: ""
  newsapi_key: ""
  reddit_client_id: ""
  reddit_client_secret: ""
  postgres_password: "cGFzc3dvcmQ="  # "password" in base64
  redis_password: "cmVkaXNwYXNzd29yZA=="  # "redispassword" in base64 